icap_reference:
    types:
        default:
            label: other
            service: default

        bibliography:
            label: bibliography
            service: bibliography

        filmography:
            label: filmography
            service: filmography

        discography:
            label: discography
            service: discography